name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/healthcare-backend
            
            # Pull latest code
            git pull origin main
            
            # Clean up old Docker images (prevent overload)
            echo "🧹 Cleaning up old Docker images..."
            docker image prune -af --filter "until=24h"
            
            # Stop and remove old containers
            docker-compose down
            
            # Build new image
            docker-compose build --no-cache
            
            # Start new container
            docker-compose up -d
            
            # Show status
            docker ps
            
            # Show logs
            docker-compose logs --tail=50
            
            echo "✅ Deployment completed!"
